### ISSUE TITLE
Server hang on monster removal feature

### ISSUE THREAD

**Issue by DerekWearmouth** [MLG-Fortress/PopulationDensity#89] opened 2020-07-23 04:50 UTC
Our server has been using this plugin for 2 years, over the last 3 days the server has started to crash 3-4x daily. we are running Paper Spigot Build 108 - 1.16.1. I saw a past report that it was possibly due to the scans, however i bumped the scan time from the default 6 to 24 and the crashes increased. Currently have the plugin disabled. Attached is the log of the error from one of the events. 

[CrashLog.txt](https://github.com/MLG-Fortress/PopulationDensity/files/4963881/CrashLog.txt)

**Comment by RoboMWM** [comment] 2020-07-23 04:58
Preferable to paste the log directly in here, or if it's too large, at gist.github.com and link here.

**Comment by RoboMWM** [comment] 2020-07-23 04:58
Also, some log entries prior to the crash help a lot for context.

**Comment by RoboMWM** [comment] 2020-07-23 04:59
either way, the info provided here is nothing different than #86, if you have more info (like context, since the watchdog stacktrace is pretty much identical) go ahead and post it there.

**Comment by RoboMWM** [comment] 2020-07-23 05:00
duplicate of #86 if you have more info (like context, since the log is pretty much identical) go ahead and post it there.

**Comment by RoboMWM** [comment] 2020-07-23 05:01
duplicate of #86

**Comment by RoboMWM** [comment] 2020-07-23 05:01
Duplicate of #86

**Comment by RoboMWM** [comment] 2020-07-23 23:28
Truncated log pasted here for anyone who doesn't want to bother downloading to view (e.g. on phone):

```
[00:26:45] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[00:26:45] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[00:26:45] [Paper Watchdog Thread/ERROR]: 11,-413 in 'The_Isle:
[00:26:45] [Paper Watchdog Thread/ERROR]: Load Task - none
[00:26:45] [Paper Watchdog Thread/ERROR]: Save Task - none
[00:26:45] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[00:26:45] [Paper Watchdog Thread/ERROR]: Chunk Status - minecraft:full
[00:26:45] [Paper Watchdog Thread/ERROR]: Chunk Ticket Status - minecraft:full
[00:26:45] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - minecraft:features
[00:26:45] [Paper Watchdog Thread/ERROR]: Chunk Holder Priority - 2
[00:26:45] [Paper Watchdog Thread/ERROR]: ------------------------------
[00:26:45] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[00:26:45] [Paper Watchdog Thread/ERROR]: 	PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
[00:26:45] [Paper Watchdog Thread/ERROR]: 	Stack:
[00:26:45] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.bk(IAsyncTaskHandler.java:131)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:511)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IChunkProvider.getChunkAt(SourceFile:16)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getChunkAt(CraftWorld.java:409)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.PopulationDensity.PopulationDensity.removeMonstersAround(PopulationDensity.java:1373)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.PopulationDensity.PopulationDensity.TeleportPlayerToRegion(PopulationDensity.java:1228)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.PopulationDensity.PopulationDensity.TeleportPlayer(PopulationDensity.java:1198)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.PopulationDensity.PopulationDensity.handleHomeCommand(PopulationDensity.java:1082)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.PopulationDensity.PopulationDensity.onCommand(PopulationDensity.java:770)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$5432/1577865423.run(Unknown Source)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2991/200296339.run(Unknown Source)
[00:26:45] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
```

**Comment by RoboMWM** [comment] 2020-07-23 23:31
Ok, so this is a similar issue as the other issue but not the same cause. Guess it really does help if I have it pasted here directly instead of opening a file, I guess just happen to scan those a lot more carelessly.

**Comment by RoboMWM** [comment] 2020-07-23 23:35
To mitigate, disable the remove monsters feature. This feature is invoked when players teleport to a post. I'm not sure if chunks are being generated or not when your crashes are occurring, but it could be improved to happen after the teleport as it should only be dealing with already-loaded chunks...

**Comment by Cobbet** [comment] 2020-07-24 07:43
> To mitigate, disable the remove monsters feature.

You mean by editing & recompiling the current plugin? Cause there's no config setting for it, and there doesn't seem to be an updated version yet (i'm not a programmer).

**Comment by RoboMWM** [comment] 2020-07-24 17:32
~~If the developer is unable to do so, then ya, you can do that. No need to recompile, you can just edit the plugin.yml in the jar.~~

**Comment by Cobbet** [comment] 2020-07-25 07:07
Sorry, I have no idea what I'm supposed to be doing. plugin.yml just seems to be a list of commands and perms.

**Comment by RoboMWM** [comment] 2020-07-25 16:45
Oh wait, I'm sorry, please disregard my prior comment. I thought this was a different issue. No, there is no need to recompile, ~~this config option does exist.~~ Ok I thought it did but I can't find it at a glance... maybe it doesn't.

**Comment by RoboMWM** [comment] 2020-07-25 16:52
Ok, so it's only going up to 2 chunks around the post, so it's not that many chunks... very strange for it to hang up on that... 1.16 really does have a lot of issues with loading chunks...

**Comment by DerekWearmouth** [comment] 2020-07-25 18:41
I have done some testing today and it seems that it may not be 1.16.1 that is causing the issue but rather the most recent builds of paper. on my test server i rolled back to paper 1.16.1 build 70 and have 0 errors ever, Currently in the process of finding what changed between build 70 and build 110. Once i figure it out i will see if i can manage the changes to the code.

**Comment by RoboMWM** [comment] 2020-07-25 18:52
Yea, https://github.com/TechFortress/GriefPrevention/issues/889 has also been identified to the root cause being Paper. Either way I can at least attempt delaying this removal task to occur after the player has been teleported/use PaperLib to load the chunks asynchronously.

**Closed as completed** 2020-07-25 19:15 UTC
Labels: Improvement

**Comment by Cobbet** [comment] 2020-07-26 06:34
We were getting this error in build 101, so maybe that will narrow things down a little.

**Comment by Muspah** [comment] 2020-07-26 13:08
https://github.com/PaperMC/Paper/issues/3986#issuecomment-663803581

Rolling back to Paper #93 seems to be a workaround, it worked for us too for the time being.
