### ISSUE TITLE
Latest crash report

### ISSUE THREAD

**Issue by Spoonerj1** [MLG-Fortress/PopulationDensity#75] opened 2019-07-02 01:30 UTC
My latest crash report shows PopDens as the culprit, wanted to post it here for your use.
[2019-07-01-5.log.gz](https://github.com/TechFortress/PopulationDensity/files/3347870/2019-07-01-5.log.gz)

**Comment by RoboMWM** [comment] 2019-07-02 04:46
Please use something like gist next time so I can easily view the log.

**Comment by RoboMWM** [comment] 2019-07-02 05:13
Duplicate of #69 

It's not responsible for the failed saves tho.

And it's not a crash, but a hang.

**Closed as completed by RoboMWM** 2019-07-02 05:13 UTC
