### ISSUE TITLE
Random crashes in 1.16.1

### ISSUE THREAD

**Issue by Cobbet** [MLG-Fortress/PopulationDensity#90] opened 2020-07-23 08:11 UTC
We're getting a crash like this several times a day, The server hangs and can't recover. Anyone had something like this? 
It didn't show up in testing, of course. 

`[13:13:12] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-101 (MC: 1.16.1) ---
[13:13:12] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[13:13:12] [Paper Watchdog Thread/ERROR]: ------------------------------
[13:13:12] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[13:13:12] [Paper Watchdog Thread/ERROR]: Chunk wait task info below: 
[13:13:12] [Paper Watchdog Thread/ERROR]: -139,-238 in 'World:
[13:13:12] [Paper Watchdog Thread/ERROR]: Load Task - none
[13:13:12] [Paper Watchdog Thread/ERROR]: Save Task - none
[13:13:12] [Paper Watchdog Thread/ERROR]: Chunk Holder - non-null
[13:13:12] [Paper Watchdog Thread/ERROR]: Chunk Status - minecraft:full
[13:13:12] [Paper Watchdog Thread/ERROR]: Chunk Ticket Status - minecraft:full
[13:13:12] [Paper Watchdog Thread/ERROR]: Chunk Holder Status - minecraft:features
[13:13:12] [Paper Watchdog Thread/ERROR]: Chunk Holder Priority - 2
[13:13:12] [Paper Watchdog Thread/ERROR]: ------------------------------
[13:13:12] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[13:13:12] [Paper Watchdog Thread/ERROR]: 	PID: 33 | Suspended: false | Native: false | State: TIMED_WAITING
[13:13:12] [Paper Watchdog Thread/ERROR]: 	Stack:
[13:13:12] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.park(Native Method)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.bk(IAsyncTaskHandler.java:131)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:511)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IChunkProvider.getChunkAt(SourceFile:16)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getChunkAt(CraftWorld.java:409)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.PopulationDensity.PopulationDensity.removeMonstersAround(PopulationDensity.java:1373)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.PopulationDensity.PopulationDensity.TeleportPlayerToRegion(PopulationDensity.java:1228)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.PopulationDensity.PopulationDensity.TeleportPlayer(PopulationDensity.java:1198)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		me.ryanhamshire.PopulationDensity.PopulationDensity.onCommand(PopulationDensity.java:692)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$5294/218719427.run(Unknown Source)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1203)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2956/264425599.run(Unknown Source)
[13:13:12] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[13:13:12] [Paper Watchdog Thread/ERROR]: ------------------------------
[13:13:12] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[13:13:12] [Paper Watchdog Thread/ERROR]: ------------------------------`

**Comment by RoboMWM** [comment] 2020-07-23 23:23
Duplicate of #86

**Closed as completed by RoboMWM** 2020-07-23 23:23 UTC
