### ISSUE TITLE
Server cannot start on recent spigot build 2388

### ISSUE THREAD

**Issue by Spoonerj1** [MLG-Fortress/PopulationDensity#76] opened 2019-07-03 06:58 UTC
I keep getting the same error when starting the server using this plugin:
https://pastebin.com/zJujbWNK

I can't start the server because of this.

**Comment by Spoonerj1** [comment] 2019-07-03 06:59
I have tested it against a new server with a brand new build of spigot, version 2388, and only the latest released version of PopDens. I get the same error in that clean environment, and in my main server which has other plugins.

**Comment by RoboMWM** [comment] 2019-07-04 00:22
Hmm, I'll try to see if I can delay the scanregion task from running immediately at startup. The reason why the initial scan takes place is because if an admin uses this plugin for the first time, it needs to find a place with enough resources in order to set the first region post to use.

The reason why scanRegion takes longer is there currently is no async chunk loading at all in paper or spigot, and 1.14 chunk loading/generation is a lot heavier than previous versions from what I hear.

For now, you can mitigate via setting `timeout-time` in spigot.yml to a much larger interval (the value is in seconds).

Duplicate of #69

**Closed as completed by RoboMWM** 2019-07-04 00:22 UTC
